language: python
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - python: 2.7
  - python: 2.6
  - python: 3.2
  - python: 3.3
  - python: 3.4
  - python: pypy
  allow_failures:
  - python: 3.2
  - python: 3.3
  - python: 3.4

install:
  - "pip install ."
  - "pip install -r requirements.txt"

script: nosetests
